// Country flag emojis for international tournament teams.
// Used by TournamentView + Telegram preview. Keep keys aligned with team names
// as stored in the DB (post-normalization).
const COUNTRY_FLAGS = {
  // CONMEBOL
  'Argentina':              '🇦🇷',
  'Brazil':                 '🇧🇷',
  'Uruguay':                '🇺🇾',
  'Colombia':               '🇨🇴',
  'Chile':                  '🇨🇱',
  'Peru':                   '🇵🇪',
  'Paraguay':               '🇵🇾',
  'Ecuador':                '🇪🇨',
  'Bolivia':                '🇧🇴',
  'Venezuela':              '🇻🇪',

  // UEFA
  'France':                 '🇫🇷',
  'Germany':                '🇩🇪',
  'Spain':                  '🇪🇸',
  'England':                '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Italy':                  '🇮🇹',
  'Portugal':               '🇵🇹',
  'Netherlands':            '🇳🇱',
  'Belgium':                '🇧🇪',
  'Croatia':                '🇭🇷',
  'Switzerland':            '🇨🇭',
  'Denmark':                '🇩🇰',
  'Austria':                '🇦🇹',
  'Poland':                 '🇵🇱',
  'Czechia':                '🇨🇿',
  'Turkey':                 '🇹🇷',
  'Serbia':                 '🇷🇸',
  'Hungary':                '🇭🇺',
  'Slovakia':               '🇸🇰',
  'Slovenia':               '🇸🇮',
  'Ukraine':                '🇺🇦',
  'Wales':                  '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Scotland':               '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Republic of Ireland':    '🇮🇪',
  'Ireland':                '🇮🇪',
  'Northern Ireland':       '🇬🇧',
  'Sweden':                 '🇸🇪',
  'Norway':                 '🇳🇴',
  'Finland':                '🇫🇮',
  'Iceland':                '🇮🇸',
  'Albania':                '🇦🇱',
  'Romania':                '🇷🇴',
  'Bulgaria':               '🇧🇬',
  'Bosnia-Herzegovina':     '🇧🇦',
  'Macedonia':              '🇲🇰',
  'Greece':                 '🇬🇷',
  'Russia':                 '🇷🇺',
  'Georgia':                '🇬🇪',
  'Armenia':                '🇦🇲',
  'Azerbaijan':             '🇦🇿',
  'Kosovo':                 '🇽🇰',
  'Moldova':                '🇲🇩',
  'Cyprus':                 '🇨🇾',
  'Israel':                 '🇮🇱',
  'Belarus':                '🇧🇾',
  'Estonia':                '🇪🇪',
  'Latvia':                 '🇱🇻',
  'Lithuania':              '🇱🇹',
  'Luxembourg':             '🇱🇺',
  'Malta':                  '🇲🇹',
  'Montenegro':             '🇲🇪',

  // CONCACAF
  'United States':          '🇺🇸',
  'Mexico':                 '🇲🇽',
  'Canada':                 '🇨🇦',
  'Costa Rica':             '🇨🇷',
  'Jamaica':                '🇯🇲',
  'Panama':                 '🇵🇦',
  'Honduras':               '🇭🇳',
  'El Salvador':            '🇸🇻',
  'Guatemala':              '🇬🇹',
  'Haiti':                  '🇭🇹',
  'Curaçao':                '🇨🇼',
  'Cuba':                   '🇨🇺',
  'Trinidad and Tobago':    '🇹🇹',
  'Saint Kitts and Nevis':  '🇰🇳',
  'Martinique':             '🇲🇶',
  'Guadeloupe':             '🇬🇵',

  // CAF (Africa)
  'Morocco':                '🇲🇦',
  'Senegal':                '🇸🇳',
  'Tunisia':                '🇹🇳',
  'Egypt':                  '🇪🇬',
  'Algeria':                '🇩🇿',
  'Nigeria':                '🇳🇬',
  'Ghana':                  '🇬🇭',
  'Cameroon':               '🇨🇲',
  'Ivory Coast':            '🇨🇮',
  'South Africa':           '🇿🇦',
  'Mali':                   '🇲🇱',
  'Burkina Faso':           '🇧🇫',
  'Cape Verde':             '🇨🇻',
  'Guinea':                 '🇬🇳',
  'Congo DR':               '🇨🇩',
  'Angola':                 '🇦🇴',
  'Mauritania':             '🇲🇷',
  'Zambia':                 '🇿🇲',
  'Tanzania':               '🇹🇿',
  'Gambia':                 '🇬🇲',
  'Equatorial Guinea':      '🇬🇶',
  'Gabon':                  '🇬🇦',
  'Mozambique':             '🇲🇿',
  'Namibia':                '🇳🇦',
  'Comoros':                '🇰🇲',
  'Sierra Leone':           '🇸🇱',
  'Togo':                   '🇹🇬',
  'Benin':                  '🇧🇯',
  'Madagascar':             '🇲🇬',

  // AFC (Asia)
  'Japan':                  '🇯🇵',
  'South Korea':            '🇰🇷',
  'Iran':                   '🇮🇷',
  'Australia':              '🇦🇺',
  'Saudi Arabia':           '🇸🇦',
  'Qatar':                  '🇶🇦',
  'Iraq':                   '🇮🇶',
  'Jordan':                 '🇯🇴',
  'United Arab Emirates':   '🇦🇪',
  'Uzbekistan':             '🇺🇿',
  'China':                  '🇨🇳',
  'Thailand':               '🇹🇭',
  'Indonesia':              '🇮🇩',
  'Vietnam':                '🇻🇳',
  'Malaysia':               '🇲🇾',
  'Bahrain':                '🇧🇭',
  'Kuwait':                 '🇰🇼',
  'Oman':                   '🇴🇲',
  'Lebanon':                '🇱🇧',
  'Syria':                  '🇸🇾',
  'Palestine':              '🇵🇸',
  'Tajikistan':             '🇹🇯',
  'Kyrgyzstan':             '🇰🇬',
  'India':                  '🇮🇳',
  'Hong Kong':              '🇭🇰',

  // OFC (Oceania)
  'New Zealand':            '🇳🇿',
  'Fiji':                   '🇫🇯',
  'Papua New Guinea':       '🇵🇬',
  'Solomon Islands':        '🇸🇧',
  'Vanuatu':                '🇻🇺',
  'Tahiti':                 '🇵🇫',
};

export function flagFor(team) {
  if (!team) return '';
  return COUNTRY_FLAGS[team] || '';
}

export default COUNTRY_FLAGS;
